### ISSUE TITLE
creating component from GitLab requires 2 annotations

### ISSUE THREAD

**Issue by jhutar** [konflux-ci/docs#118]
When I attempt to on-board private component on company internal GitLab instance, I was pointed at this documentation:

https://docs.google.com/document/d/1bKE4pmrufEb1QROo7XhMVEmUClc--WtAmX1__rxNscc/edit#bookmark=id.u7p3l2ih7byb

That mentions 2 annotations that are not mentioned in Konflux docs: "git-provider" and "git-provider-url". This is a complete component YAML I have used:

```
apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  annotations:
    build.appstudio.openshift.io/pipeline: '{"name":"docker-build","bundle":"latest"}'
    build.appstudio.openshift.io/request: configure-pac
    git-provider: gitlab
    git-provider-url: https://gitlab.example.com
  name: myrepo
  namespace: jhutar-tenant
spec:
  application: something
  componentName: myrepo
  resources: {}
  source:
    git:
      url: https://gitlab.example.com/something/myrepo
      context: ./
      dockerfileUrl: Containerfile
      revision: main
```

IMHO these two annotations should be mentioned in the docs.
